;; move between windows
;; (defhydra hydra-window (global-map "C-c m")
;; "A hydra for moving windows"
;; ("h" windmove-left)
;; ("j" windmove-down)
;; ("k" windmove-up)
;; ("l" windmove-right)
;; ("J" (lambda ()
;; (interactive)
;; (split-window-below)
;; (windmove-down)))
;; ("K" (lambda ()
;; (interactive)
;; (split-window-right)
;; (windmove-right)))
;; ("x" delete-other-windows "one" :color blue)
;; ("t" transpose-frame "'")
;; ("a" ace-window "ace")
;; ("s" ace-swap-window "swap")
;; ("d" ace-delete-window "del")
;; ("m" ace-maximize-window "ace-one" :color blue)
;; ("b" ido-switch-buffer "buf")
;; ("q" nil "cancel"))

(provide 'o-hydras)
